name: Generate PDF from Markdown

on:
  push:
    branches:
      - main  # Le workflow se déclenche sur un push dans la branche "main".

jobs:
  build:
    runs-on: ubuntu-latest  # Le workflow s'exécute sur un runner Ubuntu

    steps:
      # Étape 1 : Vérifier le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Pandoc et WeasyPrint (moteur de PDF)
      - name: Install Pandoc and WeasyPrint
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc python3-pip
          pip3 install weasyprint

      # Étape 3 : Convertir le fichier Markdown en PDF avec WeasyPrint
      - name: Generate PDF from Markdown using WeasyPrint
        run: |
          pandoc README.md -o README.pdf --pdf-engine=weasyprint

      # Étape 4 : Télécharger le PDF généré comme artefact
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-pdf
          path: document.pdf
